function Hd = notch_6000
%NOTCH_6000 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.5 and Signal Processing Toolbox 8.1.
% Generated on: 07-May-2019 09:43:25

% Equiripple Bandstop filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 44000;  % Sampling Frequency

Fpass1 = 4750;            % First Passband Frequency
Fstop1 = 5750;            % First Stopband Frequency
Fstop2 = 6250;            % Second Stopband Frequency
Fpass2 = 7250;            % Second Passband Frequency
Dpass1 = 0.028774368332;  % First Passband Ripple
Dstop  = 0.031622776602;  % Stopband Attenuation
Dpass2 = 0.057501127785;  % Second Passband Ripple
dens   = 20;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass1 Fstop1 Fstop2 Fpass2]/(Fs/2), [1 0 ...
                          1], [Dpass1 Dstop Dpass2]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
